# Generated by Django 5.2.6 on 2025-09-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=25)),
                ('real_name', models.CharField(max_length=25)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('active_since', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
