services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"