services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"